# 1.4.4 Smoothing Images

## Kernel Convolution

In [16]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [17]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [18]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [19]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [20]:
img

array([[5, 7, 4, 6, 0, 2, 9, 4, 0, 2, 7, 5],
       [0, 6, 5, 0, 8, 1, 9, 4, 7, 9, 0, 1],
       [1, 8, 4, 9, 5, 3, 9, 1, 9, 9, 1, 5],
       [5, 8, 8, 9, 5, 4, 5, 7, 0, 1, 2, 8],
       [7, 7, 5, 1, 7, 9, 1, 4, 6, 7, 9, 1],
       [7, 6, 0, 1, 7, 4, 8, 3, 7, 3, 6, 7],
       [0, 0, 1, 6, 5, 8, 8, 5, 9, 4, 6, 3],
       [4, 1, 0, 4, 4, 3, 5, 9, 5, 7, 1, 1],
       [4, 0, 4, 8, 4, 5, 1, 9, 1, 0, 1, 4],
       [1, 7, 5, 9, 3, 1, 5, 9, 3, 8, 6, 4],
       [2, 0, 1, 1, 1, 6, 5, 4, 0, 3, 1, 5],
       [3, 7, 2, 3, 4, 2, 1, 0, 3, 9, 3, 4]])

In [21]:
h,w=img.shape

In [22]:
print(h,w)

12 12


In [23]:
#[*range(-2,3)]

In [ ]:
dst = np.zeros((h,w),np.int)

In [ ]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [26]:
img

array([[5, 7, 4, 6, 0, 2, 9, 4, 0, 2, 7, 5],
       [0, 6, 5, 0, 8, 1, 9, 4, 7, 9, 0, 1],
       [1, 8, 4, 9, 5, 3, 9, 1, 9, 9, 1, 5],
       [5, 8, 8, 9, 5, 4, 5, 7, 0, 1, 2, 8],
       [7, 7, 5, 1, 7, 9, 1, 4, 6, 7, 9, 1],
       [7, 6, 0, 1, 7, 4, 8, 3, 7, 3, 6, 7],
       [0, 0, 1, 6, 5, 8, 8, 5, 9, 4, 6, 3],
       [4, 1, 0, 4, 4, 3, 5, 9, 5, 7, 1, 1],
       [4, 0, 4, 8, 4, 5, 1, 9, 1, 0, 1, 4],
       [1, 7, 5, 9, 3, 1, 5, 9, 3, 8, 6, 4],
       [2, 0, 1, 1, 1, 6, 5, 4, 0, 3, 1, 5],
       [3, 7, 2, 3, 4, 2, 1, 0, 3, 9, 3, 4]])

In [ ]:
dst

In [28]:
img = cv2.imread('lena.png', 0)

In [29]:
h,w=img.shape

In [30]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [31]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [32]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()